Add hosts entry to VM

diff --git a/kubernetes/azure/devops-pipelines/templates/get-bastion-node-ip.yaml b/kubernetes/azure/devops-pipelines/templates/get-bastion-node-ip.yaml
--- a/kubernetes/azure/devops-pipelines/templates/get-bastion-node-ip.yaml
+++ b/kubernetes/azure/devops-pipelines/templates/get-bastion-node-ip.yaml
@@ -14,18 +14,19 @@
 # specific language governing permissions and limitations
 # under the License.
 
-- task: AzureCLI@2
-  displayName: 'Get Bastion Node IP dynamically'
-  inputs:
-    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
-    scriptType: bash
-    scriptLocation: inlineScript
-    inlineScript: |
-      # Get the IP address of the bastion node
-      BASTION_IP=$(az vm show -g $(RESOURCE_GROUP_NAME) -n $(VM_NAME) --show-details --query publicIps -o tsv)
-      if [ -z "$BASTION_IP" ]; then
-        echo "##vso[task.logissue type=error]Failed to retrieve Bastion Node IP"
-        exit 1
-      fi
-      echo "Bastion Node IP: $BASTION_IP"
-      echo "##vso[task.setvariable variable=BASTION_NODE_IP]$BASTION_IP"
+steps:
+  - task: AzureCLI@2
+    displayName: 'Get Bastion Node IP dynamically'
+    inputs:
+      azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        # Get the IP address of the bastion node
+        BASTION_IP=$(az vm show -g $(RESOURCE_GROUP_NAME) -n $(VM_NAME) --show-details --query publicIps -o tsv)
+        if [ -z "$BASTION_IP" ]; then
+          echo "##vso[task.logissue type=error]Failed to retrieve Bastion Node IP"
+          exit 1
+        fi
+        echo "Bastion Node IP: $BASTION_IP"
+        echo "##vso[task.setvariable variable=BASTION_NODE_IP]$BASTION_IP"
